<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="employee"
    nsURI="http:///org.eclipse.gmf.tests.runtime.emf.type.core/Employee.ecore" nsPrefix="Employee">
  <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="salary" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="band" lowerBound="1" eType="#//Band"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityClearance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" lowerBound="1"
        eType="#//Department" eOpposite="#//Department/members"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="office" lowerBound="1"
        eType="#//Office" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Band">
    <eLiterals name="junior"/>
    <eLiterals name="senior" value="1"/>
    <eLiterals name="manager" value="2"/>
    <eLiterals name="director" value="3"/>
    <eLiterals name="executive" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Department" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Employee" containment="true" eOpposite="#//Employee/department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manager" lowerBound="1"
        eType="#//Employee" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Office" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfWindows" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasDoor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coop" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Client" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="represents" eType="#//Customer"
        eOpposite="#//Customer/representatives"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//EModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representatives" upperBound="-1"
        eType="#//Client" containment="true" eOpposite="#//Client/represents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsidiaries" upperBound="-1"
        eType="#//Customer" containment="true" eOpposite="#//Customer/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Customer"
        eOpposite="#//Customer/subsidiaries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HighSchoolStudent" eSuperTypes="#//Student"/>
</ecore:EPackage>
